// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Popularnosc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Popularnosc));
        
        string IMigrationMetadata.Id
        {
            get { return "201610101929242_Popularnosc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
